############################## LOGIN ##############################
###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "hellas",
    "password": "salainen"
}


############################## BLOGS ##############################
###
GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjhlY2ZlODVmMDkxZmRlZWM0NzQ4YzhlIiwiaWF0IjoxNzYwMzY1MDA3fQ.0mdyrbPawUb9Iqi_gNzgQ40jnt_pZDygF02O-CZ4QLQ

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 20
}

############################## USERS ##############################
###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "hellas",
    "name": "Arto Hellas",
    "password": "salainen"
}