GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/info/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "lol",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/68e812aa97d7158406d55d0d HTTP/1.1