GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/info/

###
GET http://localhost:3001/api/persons/68e816d3a423fc2edcac144a

###
DELETE http://localhost:3001/api/persons/68e816d3a423fc2edcac144a

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "New Person",
    "number": "111-2222-444"
}